### ISSUE TITLE
Multiple players in top episode & none below

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-web-player#384] opened 2017-06-05 15:13 UTC
## Issue:
The top episode on the frontpage displays multiple web players (different episodes). All episodes below display none. 

![4 alpha problem](https://cloud.githubusercontent.com/assets/11300164/26789651/3d4a1ec0-4a11-11e7-812b-d25c8bcc24c7.png)

The amount of players is equal to the amount of episodes on the frontpage. In other words: The players for episodes `2` to `n` (where the latest one on top is `1`) will be inserted in the first post below the player for `1`.

> Website                    https://GameTalk.FM
> PHP Version                5.6.30
> WordPress Version          4.7.5
> WordPress Theme            Joeys Twenty Fifteen Child v1.0
> WordPress Database Charset utf8
> WordPress Database Collate 
> Publisher Version          2.6.0
> Web Player Version         no web player found
> Twig Version               1.33.2
> open_basedir               ok
> curl Version               7.36.0
> iconv                      available
> simplexml                  ok
> max_execution_time         50
> upload_max_filesize        100M
> memory_limit               256M
> disable_classes            
> disable_functions          exec, shell_exec, system, dl, passthru, proc_open, proc_close
> permalinks                 ok (/%postname%/)
> podlove_permalinks         ok
> podcast_settings           ok
> web_player                 ok
> podlove_cache              on
> assets                     
>   - mp3    audio/mpeg       https://GameTalk.FM/feed/mp3/
>   - m4a    audio/mp4        https://GameTalk.FM/feed/m4a/
> cron                       ok
> 
> 0 errors
> 0 notices
> Nice, Everything looks fine!

**Comment by alexander-heimbuch** [comment] 2017-06-05 17:43
Thanks for the report, we will try to reproduce the error and research the cause.

**Comment by eteubert** [comment] 2017-06-27 06:44
Was a bug in the Publisher, fixed with https://github.com/podlove/podlove-publisher/releases/tag/2.6.2

**Closed by eteubert** 2017-06-27 06:44 UTC
Labels: bug
